name: chopper_example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.1.0-dev
  state_notifier: ^0.5.0
  flutter_state_notifier: ^0.4.2
  freezed_annotation:
  chopper: 3.0.3
  cupertino_icons: ^0.1.3
  flutter_stetho: 0.5.2
  cached_network_image: 2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  build_runner: ^1.0.0
  chopper_generator: 3.0.5

flutter:
  uses-material-design: true

